# Site settings
baseurl = "https://blog.balashekhar.me/"
title = "bala's random rumblings"
pagination.pagerSize = 4
buildFuture = true

[[menu.social]]
  name = "GitHub"
  title = "fab fa-github-square"
  url = "https://github.com/baala3"

[[menu.social]]
  name = "Portfolio"
  title = "fa fa-user"
  url = "https://dev.balashekhar.me/"

[[menu.main]]
  name = "Talks"
  title = "Talks"
  url = "/talks/"

[[menu.main]]
  name = "Slides"
  title = "Slides"
  url = "/slides/"

[[menu.main]]
  name = "Archives"
  title = "Archives"
  url = "/archives/"

[params]
  author = "bala"
  twitter = "balashekhar_k"
  classes = []

[outputs]
  home = ["HTML", "JSON", "RSS"]
  page = ["HTML"]
  section = ["HTML", "RSS"]
  taxonomy = ["HTML", "RSS"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    style = "solarized-light"
